Make argument an array
contao-community-alliance/composer-plugin pull request #88
Opened 2022-03-30 11:42 UTC by bytehead

See #87

2022-03-30 11:45 UTC, Toflar approved these changes
This was changed in 4.2 so we don't need a BC layer here.

2022-03-30 11:45 UTC, Toflar requested changes
But the arguments need to be separated, no?

2022-03-30 11:46 UTC, bytehead commented
Could possibly, I'll check.

2022-03-30 11:50 UTC, bytehead commented
Changed in 9d5d93f accordingly.

2022-03-30 11:51 UTC, Toflar approved these changes

2022-03-30 16:24 UTC, fritzmg commented
This will break compatibility with previous composer versions (and thus possibly also the Contao Manager - not sure though @aschempp).

2022-03-30 19:23 UTC, bytehead commented
@fritzmg You're right, Composer itself ships before 2.3.0 with `symfony/process` in `2.8.x`. 
I've added a fallback in deed078.

2022-03-30 19:37 UTC, Toflar commented on src/UserFilesLocator.php
> +            $arguments = $this->getConsolePath() . ' debug:container --parameter=contao.upload_path';
```suggestion
            $arguments = implode(' ', $arguments);
```

2022-03-30 20:24 UTC, bytehead commented on src/UserFilesLocator.php
> +            $arguments = $this->getConsolePath() . ' debug:container --parameter=contao.upload_path';
Nice 💪

2022-03-30 20:24 UTC, bytehead commented on src/UserFilesLocator.php
> +            $arguments = $this->getConsolePath() . ' debug:container --parameter=contao.upload_path';
Adjusted in 169f383.

2022-03-30 20:47 UTC, Toflar approved these changes

2022-03-31 07:45 UTC, fritzmg approved these changes
Btw. this is how the Contao Manager Bundle's Composer plugin checks for it:

https://github.com/contao/contao/blob/fd1a75351dfb8a88dd92982b6a83ffd1a54518f3/manager-bundle/src/Composer/ScriptHandler.php#L80-L83

But checking the composer version is fine too :)

2022-03-31 09:07 UTC, aschempp commented
I think we should go with the `setCommandline` check. The `symfony/process` version in the Contao Manager is different from what the pre-build `composer.phar` contains, since we only support PHP 7.1+ by default. Checking for `setCommandline` should handle all use cases.

2022-03-31 09:08 UTC, bytehead commented
I don't get the correlation between the argument type hinting and `setCommandline`? 🤔

2022-03-31 09:10 UTC, fritzmg commented
> I don't get the correlation between the argument type hinting and `setCommandline`? 🤔

The `symfony/process` version that introduced support for the array argument also introduced that method.

2022-04-01 10:28 UTC, leofeyer commented
We should merge this ASAP, because Contao can no longer be installed with Composer 2.3.

<img width="787" alt="" src="https://user-images.githubusercontent.com/1192057/161246301-c8026d7c-c820-4f02-9bb5-dc20d71480f7.png">

2022-04-01 14:41 UTC, leofeyer approved these changes

2022-04-01 14:56 UTC, merged